/*
 * ESP32 Certificates Header File
 * 
 * IMPORTANT: Replace the certificate contents below with your actual certificates
 * generated by gen_certs.py
 * 
 * To get the certificates:
 * 1. Run: python gen_certs.py
 * 2. Copy content from certs/root_ca.pem to ca_cert below
 * 3. Copy content from certs/{MAC_ADDRESS}.crt to device_cert below
 * 4. Copy content from certs/{MAC_ADDRESS}.key to device_key below
 */

#ifndef ESP32_CERTS_H
#define ESP32_CERTS_H

// Root CA Certificate (for verifying ThingsBoard server)
// Generated from: certs/root_ca.pem
const char* ca_cert = \
"-----BEGIN CERTIFICATE-----\n" \
"MIIDMzCCAhugAwIBAgIUVB14mQ/WhL+2mbFoMHw2dOIAgvcwDQYJKoZIhvcNAQEL\n" \
"BQAwQTELMAkGA1UEBhMCVk4xFDASBgNVBAoMC1RoaW5nc0JvYXJkMRwwGgYDVQQD\n" \
"DBNUaGluZ3NCb2FyZCBSb290IENBMB4XDTI2MDEwNjA3MzIyN1oXDTM2MDEwNDA3\n" \
"MzIyN1owQTELMAkGA1UEBhMCVk4xFDASBgNVBAoMC1RoaW5nc0JvYXJkMRwwGgYD\n" \
"VQQDDBNUaGluZ3NCb2FyZCBSb290IENBMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A\n" \
"MIIBCgKCAQEApdXkvSgHeqQ1rUD9//hu3aMfBfjbBfVR6zWwsDkuJwSu4wOEP7iw\n" \
"9rLmOT4Yw33sfR23HQpeug3ERddc0AwOoEd1PI45nDqsWIFjJ/QOd4omdTKKBAHo\n" \
"CHYMqCjfadCNlXvd0uJqG/8pcBfak+mrdPNjPQlrHSl3wICrPfOSwYlJtiRNTC+V\n" \
"OfFHZUh2L5FerLDFle7gz26Po4i2L4UvgvBsKoVtq4LxukAOc0B2/HhTXyS+oOMu\n" \
"9wUl0MUEhnYGsPhINmACnhTEX4AG7w3RQg+xoKaxutjPccegYCPHxhh4/sl/UtNB\n" \
"Ew12E/8jy07wSyrMicyWWJvNPii2g1xbNwIDAQABoyMwITAPBgNVHRMBAf8EBTAD\n" \
"AQH/MA4GA1UdDwEB/wQEAwIBhjANBgkqhkiG9w0BAQsFAAOCAQEABkmyVI5manj9\n" \
"JX1CqYay9GH/1t1vlG9TbnHvt5ZC73tWmy/HdRdCoomG2F3TZ+qxJj0IhpOSPsSA\n" \
"prZF7xP54qCGS+kmuQcbTm3ey80w0mVx5GFXWNUATXxCachhM1xkAWNPuAt1344i\n" \
"7gP+i3rwX6z7CLI58BgZu9SFNaU2m3b6Iiqq2FwhEF9v6o1VhoOigQQj84BxdVUm\n" \
"6xpNRksY4qSwZ+nfOvFwWejGG36rJ98x0SCawNNNS6JoRRomy9oTtNu5cI1IKkQh\n" \
"fBikJ0pGbjrtQPTb+lUgD3hA0HaWt9kZNj76xK9ZDSAIS0xfIrwle0+jN58hvbGQ\n" \
"bfbWOS/oXg==\n" \
"-----END CERTIFICATE-----\n";

// Device Certificate (for client authentication)
// Generated from: certs/A842E3578AD4.crt
const char* device_cert = \
"-----BEGIN CERTIFICATE-----\n" \
"MIIDQzCCAiugAwIBAgIUDUXx9k7gStjdUMFjZD6h2O8CD0wwDQYJKoZIhvcNAQEL\n" \
"BQAwQTELMAkGA1UEBhMCVk4xFDASBgNVBAoMC1RoaW5nc0JvYXJkMRwwGgYDVQQD\n" \
"DBNUaGluZ3NCb2FyZCBSb290IENBMB4XDTI2MDEwNjA3MzIyN1oXDTM2MDEwNDA3\n" \
"MzIyN1owPDELMAkGA1UEBhMCVk4xFjAUBgNVBAoMDUVTUDMyIERldmljZXMxFTAT\n" \
"BgNVBAMMDEE4NDJFMzU3OEFENDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC\n" \
"ggEBAI7N6Jq6Fi+aK58rfsAFnae8juTV7HJ5OTUC2KLuZMP9zqHhz0P5WXm+SpzE\n" \
"QaE1u4UGHpkXjt2kSHr7O6CEKfJ8MB2UffH1TF7Xt7LCSiYaaucry/3+ntb+tevs\n" \
"nWzw6gUVEDGfcKvBHYx1AsaL6dkJaJyFeSgSMEHEukievp/qbwVsEyMbM5i/7y3w\n" \
"chS0KreEDpe1QjyKVQULqH2heZukRlu6pNaHFqJy+tFn9mAu935+j2YAcW1fQKCu\n" \
"rvxXBl/C8TTu+Nl4v6dSGWYYriuFoeizJGIIokvOB/osaoM7ZVssImnxJg7ZOxFM\n" \
"n29U4lvcIgV34Pf0wduzbovVar8CAwEAAaM4MDYwDAYDVR0TAQH/BAIwADAOBgNV\n" \
"HQ8BAf8EBAMCBaAwFgYDVR0lAQH/BAwwCgYIKwYBBQUHAwIwDQYJKoZIhvcNAQEL\n" \
"BQADggEBACSmcTf7J0IJPrYvikhca1IOPw0SVp5CPJHKe0RLd8QgG07XeasfEhGX\n" \
"9VBfpfI+0l0TVfgZr8gECDfsvb4p/n2jiQY5dVqQJAd04mobVAxSXs9bIs8zPlSs\n" \
"sUzkFD4sSNnaNpZrabma6ruDlG9sZ23p6AGsl2i1Rp52Vz9QOQUY3BlHWolp2hbr\n" \
"4y6DZu6JjCnsZ9vntRT7FFT3l3Rz4TReWmIeQMjlXedhHaEUaLtH65tLBRQFCz8l\n" \
"ilgrhhTINbuo+MOJmC1dwkSaiCyDD1jWJvR2B6gVxgVoE7muYIaiU0lU7IVc0JSy\n" \
"iGAjfs4rZoMOEQ20AgkEGntGBAKQebU=\n" \
"-----END CERTIFICATE-----\n";

// Device Private Key (for client authentication)
// Generated from: certs/A842E3578AD4.key
const char* device_key = \
"-----BEGIN RSA PRIVATE KEY-----\n" \
"MIIEogIBAAKCAQEAjs3omroWL5ornyt+wAWdp7yO5NXscnk5NQLYou5kw/3OoeHP\n" \
"Q/lZeb5KnMRBoTW7hQYemReO3aRIevs7oIQp8nwwHZR98fVMXte3ssJKJhpq5yvL\n" \
"/f6e1v616+ydbPDqBRUQMZ9wq8EdjHUCxovp2QlonIV5KBIwQcS6SJ6+n+pvBWwT\n" \
"IxszmL/vLfByFLQqt4QOl7VCPIpVBQuofaF5m6RGW7qk1ocWonL60Wf2YC73fn6P\n" \
"ZgBxbV9AoK6u/FcGX8LxNO742Xi/p1IZZhiuK4Wh6LMkYgiiS84H+ixqgztlWywi\n" \
"afEmDtk7EUyfb1TiW9wiBXfg9/TB27Nui9VqvwIDAQABAoIBABNMnqfyiDcMteKA\n" \
"BVQ8Lg9SO1mP07Gw0ltotBBo+XNHZNqZ4uID2+TJI9pF57y6v0n+BrqX5XXs0uLT\n" \
"+z35PpYH1JTa0Z6WkSisLKZa/Zxiq5nsYFhGRf82Uy28P5ZOhMIFE7gxHRAJPE4U\n" \
"LjjZBdSQIfQtUa9prd3lkWtpEMgZuhHhokiG5PLQxiDsCBsaj3+PDavdr+Eq+KBL\n" \
"fINF+tO/AZWARSvIFur2RJFTQY0dDwNnzbj7JwVmX3YRw74yASLpxOWceTDJf5s9\n" \
"zqz5h3tG3iEp5MkApYuBwQYtAYFFFUF1hcPAlmfVjbkFobCj/zi527YbuAGLmApW\n" \
"k3ib8gkCgYEAwdUi3tZ8jxkLeEPXK3OSt1zUggxRyeMmVWdmCDrkfgx7wA0wfdsr\n" \
"f8ESPZ4TNdDrzYpDVbM9L/UvQaVSTFqfXPO5uPz7i2WKVY32IkDRAXpyf2HMYxc0\n" \
"0UVipvHantSh1IC0xhVCBnOX+Kj8lbM9vZIvumG5kdH+G/dMdh/CDjMCgYEAvJsJ\n" \
"LYf7lUZlneoQsNFSoJXHILUHRlIyqnU1HAiDDocoI6w4gkIbQimEIXqro+fG2G6k\n" \
"zo77ypKYFQ0wHDk1f7dkAveK8klk4RpjR8sQzVvFFUnE99Yo3T804VaIM5ya0okq\n" \
"pNA1UZkAaY4qjupCNtTqKM3QkrBHeYbo7Un1DUUCgYApd/Tm4dJyNvR6PWFaXXaF\n" \
"HiokzIfu/lbkLKPqnNbnlLohA3Fda7dptJ+3aQtJFzJrnen7+sXbbcQ3ciwiQ70W\n" \
"gNo6Fn2mfAnVdfKzr1RH0a+PSxgUFxHot8R8XP/dvTYGJacHPeMLSE26GEU5rchG\n" \
"t3DYmjG+XcPUrdrA5th4ewKBgD+Y+8BJsVEFuvBD5DrrarRRrSLfSEOzJfiKq0z3\n" \
"pdG5S5Sz1x49Ulm+DBsJ9WTAnDGRJautVURaqEO4/bcWp26YlXXWqRjIHOc28bFc\n" \
"zR6iSlPCW1PC+GaakKdHeYgFz8Mck6+dsc0BDb2KPdmRLqC0rPzzYdiE7qURE+wn\n" \
"2yUNAoGAfHW6+4i61uBp1voT/WajaeliXKjIZ4mpOOvuBlmYLfCbHTSVTFb1yMFP\n" \
"w1V6rzuW92f20RbpYdLzZDtDFmBFgkCN3JKtxmOImuHrBJqicyLcflm5Blj/5U3O\n" \
"psoCy51+6hQg8J5CQU851lCVMSSTlaMZAKCSRQoBNwxx1gtPdws=\n" \
"-----END RSA PRIVATE KEY-----\n";

#endif // ESP32_CERTS_H
